[[feed]]
title = "Spotify"
url = "https://engineering.atspotify.com/"
articleSelector = "li.post article"
titleSelector = "h2"
linkSelector = "h2 a"
imageSelector = ".image-holder a img"
dateSelector = ".date"
dateFormat = "January 2, 2006"


[[feed]]
title = "Futur"
url = "https://thefutur.com/blog"
articleSelector = ".blog-post"
titleSelector = ".wiz-blog-title-text"
linkSelector = "a"
imageSelector = ".blog-thumbnail"
dateSelector = ".last-blog"
dateFormat = "1.2.2006"


[[feed]]
title = "DataDog"
url = "https://datadoghq.com/blog/index.xml"
feedURL = true

[[feed]]
title = "Sentry"
url = "https://blog.sentry.io/feed.xml"
feedURL = true

[[feed]]
title = "GooleDevops"
url = "https://cloudblog.withgoogle.com/products/devops-sre/rss/"
feedURL = true

[[feed]]
title = "RiotGames"
url = "https://technology.riotgames.com/news/feed"
feedURL = true

[[feed]]
title = "Auth0"
url = "https://auth0.com/blog/rss.xml"
feedURL = true
