name: Publish RSS feeds to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every day at 5:30 and 17:30:
    - cron:  '30 5,17 * * *'
  workflow_dispatch:

jobs:
  publish-feeds:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        ref: gh-pages
      
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "hawkpro-1/feed"
        file: "rssgen"
        target: "rssgen"

    - name: exec
      run: | 
        sudo chmod +x rssgen
        sudo cp rssgen /usr/bin/rssgen
        rssgen
    
    - name: Deploy to GitHub Pages
      run: |
        git config user.name $GITHUB_ACTOR
        git config user.email $GITHUB_ACTOR@users.noreply.github.com
        git remote add gh-pages-remote https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git fetch --no-recurse-submodules
        git worktree add ./gh-pages gh-pages
        cd gh-pages
        git rm -r .
        cp -r ../public/. .
        git add .
        git commit --message="Deploying to GitHub Pages from $GITHUB_SHA"
        git push gh-pages-remote gh-pages:gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
